name: safe_browsing
description: Using google safe browsing API to detect whether the URL is safe.
version: 0.1.0-rc.2
homepage: https://github.com/vnniz/safe_browsing

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  http: ^1.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: firebase_core
      ios:
        default_package: firebase_core
      macos:
        default_package: firebase_core
      windows:
        default_package: firebase_core
      web:
        default_package: firebase_core
